### PR TITLE
docker-compose with elasticsearch setup + install.sh script

### PR DESCRIPTION
**Pull request by mysticmode**
I have done this script for production setup.

### CODE REVIEW

**Comment by mysticmode** [comment]
cc @kpcyrd @gbraad 

Run, `./install.sh`

And let me know for any improvements?

We need to add some icons to the setup to make the user interface looks good.

**Comment by gbraad** [comment]
If approved (before merging), please consider squashing the commit. For an initial review this is OK, ...

**Comment by gbraad** [comment]
? Merged before review ?

**Comment by mysticmode** [comment]
oops, sorry! I thought you said it looks OK.


On Mon, Dec 25, 2017, at 2:34 AM, Gerard Braad wrote:
> ? Merged before review ?


> — You are receiving this because you modified the open/close state.
> Reply to this email directly, view it on GitHub[1], or mute the
> thread[2].> 


Links:

  1. https://github.com/LibreRead/LibreRead/pull/25#issuecomment-353859220

**Pull request merged**
